#! /usr/bin/env python2

import sys
from lib.config import Config
from lib.plex import PlexClient

if len(sys.argv) < 2:
    print >> sys.stderr, 'Usage: {0} <section_id>'.format(sys.argv[0])
    sys.exit(1)

section_id = int(sys.argv[1])

config = Config().load()
PlexClient(config.get('plex', 'base_url')).refresh_section(section_id)
